- name: Create consul systemd service file
  template:
    src: templates/consul.service.j2
    dest: /etc/systemd/system/consul.service

- name: Start consul service
  systemd:
    name: consul
    state: started
